# Generated by Django 3.0.7 on 2024-03-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='assunto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='conteudo',
            field=models.CharField(max_length=150),
        ),
    ]
