# Generated by Django 3.0.7 on 2024-03-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_auto_20240302_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
